### GET All Transaction
GET localhost:8081/api/transactions?size=1&page=2
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUcmFzaCBBcHAiLCJpYXQiOjE3MzE4NDA0MDQsImV4cCI6MTczMTg0MDcwNCwic3ViIjoiODJjNmJjZGEtOGNmYS00MGRhLTkwZTgtMzA5N2VjMTk2N2FkIiwicm9sZSI6IkN1c3RvbWVyIn0.d-saapPabUUy9NBAKNPHp9WRvyW0OuD8S63yzaM3GyI

### GET Get Transaction By ID
GET localhost:8081/api/transactions/6e265204-3718-4a44-8b89-3996a8b84447

### POST Create Transaction
POST localhost:8081/api/transactions
Content-Type: application/json

{
  "customerId": "bf6b331a-455a-46b3-a7bc-4daabf05426d"
}

### POST Add Transaction Detail
POST localhost:8081/api/transactions/6e265204-3718-4a44-8b89-3996a8b84447/transaction_details
Content-Type: application/json

{
  "totalTrashWeight": 10,
  "trashId": "434c1a40-5cae-4f58-83ba-5263e80835e8"
}
