### POST New Trash
POST localhost:8081/api/trashes
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUcmFzaCBBcHAiLCJpYXQiOjE3MzE4NjA4MzEsImV4cCI6MTczMTg2MTQzMSwic3ViIjoiODJjNmJjZGEtOGNmYS00MGRhLTkwZTgtMzA5N2VjMTk2N2FkIiwicm9sZSI6IkN1c3RvbWVyIn0.fy7wZd7lLoY1D2PRBjIIHHrPXaBhr-Zxi5GePk0JxoM

{
  "name": "Karet",
  "price": 1500,
  "unit": "kg"
}

### GET All Trash
GET localhost:8081/api/trashes?size=5&page=1
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUcmFzaCBBcHAiLCJpYXQiOjE3MzE4NjA4MzEsImV4cCI6MTczMTg2MTQzMSwic3ViIjoiODJjNmJjZGEtOGNmYS00MGRhLTkwZTgtMzA5N2VjMTk2N2FkIiwicm9sZSI6IkN1c3RvbWVyIn0.fy7wZd7lLoY1D2PRBjIIHHrPXaBhr-Zxi5GePk0JxoM

### GET Trash By ID
GET localhost:8081/api/trashes/c71fcdd3-56d2-4009-9ea3-f5e6ff225b0c
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUcmFzaCBBcHAiLCJpYXQiOjE3MzE4NjA4MzEsImV4cCI6MTczMTg2MTQzMSwic3ViIjoiODJjNmJjZGEtOGNmYS00MGRhLTkwZTgtMzA5N2VjMTk2N2FkIiwicm9sZSI6IkN1c3RvbWVyIn0.fy7wZd7lLoY1D2PRBjIIHHrPXaBhr-Zxi5GePk0JxoM

### DELETE Trash By ID
DELETE localhost:8081/api/trashes/13754353-61b5-40e1-a033-cd6e177f3363

### UPDATE Trash
PUT localhost:8081/api/trashes/c71fcdd3-56d2-4009-9ea3-f5e6ff225b0c
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJUcmFzaCBBcHAiLCJpYXQiOjE3MzE4NjA4MzEsImV4cCI6MTczMTg2MTQzMSwic3ViIjoiODJjNmJjZGEtOGNmYS00MGRhLTkwZTgtMzA5N2VjMTk2N2FkIiwicm9sZSI6IkN1c3RvbWVyIn0.fy7wZd7lLoY1D2PRBjIIHHrPXaBhr-Zxi5GePk0JxoM

{
  "name": "Plastik",
  "price": 15000,
  "unit": "kg"
}